Kalinga management system/Controllers/AddUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kalinga_management_system.Models;

namespace Kalinga_management_system.Controllers
{
    public class AddUserController : Controller
    {
        // GET: AddUser

        private readonly ManagerModel managerModel = new ManagerModel();

        [HttpGet]
        public ActionResult GetAndAddLead()
        {
            try
            {
                LeadModel leadModel = new LeadModel();

                return View(leadModel);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;

                return View();
            }

            
        }
        [HttpPost]
        public ActionResult GetAndAddLead(LeadModel lead)
        {
            try
            {
                int value = managerModel.AddLeadDetail(lead);

                if (value > 0)
                {

                    return View();
                }
                else
                {
                    ViewBag.message = "Failed to add data into database !!!";
                    return View();
                }
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;

                return View();
            }

            
        }





        [HttpGet]
        public ActionResult GetAndAddMind()
        {
            try
            {
                MindModel mindModel = new MindModel();
                List<LeadModel> context = managerModel.GetAllLeadsDetailsFromDatabase();

                if (context != null)
                {
                    ViewBag.leads = context;
                }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;

                return View();
            }
            
        }


        [HttpPost]
        public ActionResult GetAndAddMind(MindModel mindModel, LeadModel leadModel)
        {
            try
            {
                ViewBag.leads = managerModel.GetAllLeadsDetailsFromDatabase();

                int value = managerModel.AddMindDetail(mindModel, leadModel);
                if (value > 0)
                {
                    return View();
                }
                else
                {
                    ViewBag.message = "Failed to add data into database !!!";
                    return View();
                }
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;

                return View();
            }

           
        }


    }
}

Kalinga management system/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kalinga_management_system.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Kalinga management system/Controllers/ShowAndUpdateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kalinga_management_system.Models;

namespace Kalinga_management_system.Controllers
{
    public class ShowAndUpdateController : Controller
    {
        // GET: ShowAndUpdate
        private readonly ManagerModel managerModel = new ManagerModel();


        [HttpGet]
        public ActionResult GetLeadModelDetail()
        {
            try
            {
                List<LeadModel> leadModels = managerModel.GetAllLeadsDetailsFromDatabaseDatabase();
                return View(leadModels);

            }
            catch (Exception e)
            {
                ViewBag.message = e.Message;
                return View();
            }
        }


        [HttpGet]
        public ActionResult UpdateLeadDetail(int id)
        {
            return View(managerModel.GetAllLeadsDetailsFromDatabase().Find(LeadModel => LeadModel.LeadId == id));
        }

        [HttpPost]
        public ActionResult UpdateLeadDetail(LeadModel leadModel)
        {

            int rowAffected = managerModel.UpdateLeadDetail(leadModel);

            if (rowAffected > 0)
            {
                return View();
            }
            else
            {
                ViewBag.ErrorMessage = "Failed to Update Details Try again ! ! !";
                return View(managerModel.GetAllLeadsDetailsFromDatabase().Find(LeadModel => leadModel.LeadId == leadModel.LeadId));
            }
        }




        
        [HttpGet]

        public ActionResult MindModelDetail()
        {
            try
            {
                List<MindModel> mindModels = managerModel.GetAllMindsDetailsFromDatabase();
                return View(mindModels);
            }
            catch (Exception ex)
            {

                ViewBag.message = ex.Message;
                return View();
            }
        }

        [HttpGet]
        public ActionResult UpdateMindDetail(int id)
        {
            ViewBag.Leads = managerModel.GetAllLeadsDetailsFromDatabase();
            return View(managerModel.GetAllMindsDetailsFromDatabase().Find(MindModel => MindModel.MindId == id));
        }

        [HttpPost]
        public ActionResult UpdateMindDetail(MindModel mindModel, LeadModel leadModel)
        {
            ViewBag.Leads = managerModel.GetAllLeadsDetailsFromDatabase();
            int rowAffected = managerModel.UpdateMindDetail(mindModel, leadModel);

            if (rowAffected > 0)
            {
                return View();
            }
            else
            {
                ViewBag.ErrorMessage = "Failed to Update Details Try again ! ! !";
                ViewBag.Leads = managerModel.GetAllLeadsDetailsFromDatabase();
                return View(managerModel.GetAllMindsDetailsFromDatabase().Find(MindModel => MindModel.MindId == leadModel.LeadId));
            }
        }
    }
}

Kalinga management system/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Kalinga management system/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Kalinga management system/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Kalinga</h1>
    <p class="lead">
        Mindtree Kalinga is our first residential campus spread across 20 acres of the most beautiful
        landscape in Bhubaneswar, India. The campus layout and functionality is inspired by natural landscape, local flora and fauna,
        community art and ancient Odisha architecture to provide a global workplace for the Mindtree
        Minds of the future.
    </p>
    <p><a href="https://www.mindtree.com/" class="btn btn-primary btn-lg">Explore More &raquo;</a></p>
    <p><a href="https://www.mindtree.com/sites/default/files/2019-09/mindtree-kalinga-campus-advisory-29-jun-19.pdf" class="btn btn-primary btn-lg">Read more about Kalinga &raquo;</a></p>
</div>

<div class="row">
    @*<div class="col-md-4">
            <h2>Add Minds and Leads</h2>
            <p>
                Through this portal you can add information about new minds and Leads, Get there details and put then through here
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>*@
    <div class="col-md-5">
        <h2>Add Mind and Leads</h2>
        <p>
            Through this portal you can add information about new minds and Leads, Get there details and put then through here to
            database of kalinga,
        </p>
        <p>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Add Details</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Add Minds and their Detail", "GetAndAddMind", "AddUser")</li>
                            <li>@Html.ActionLink("Add Leads and their Detail", "GetAndAddLead", "AddUser")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </p>
    </div>
    @*<div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>*@
    <div class="col-md-5">
        <h2>View Mind and Leads</h2>
        <p>
            Using this portal you can View All the minds and leads available in Database Also You can update their Detail
        </p>
        <p>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Add Details</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Show All Minds and their Detail with update access", "MindModelDetail", "ShowAndUpdate")</li>
                            <li>@Html.ActionLink("Show All Leads and their Detail with update access", "GetLeadModelDetail", "ShowAndUpdate")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </p>
    </div>
    @*<div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>*@
</div>